### ISSUE TITLE
coveralls.io leaks your information

### ISSUE THREAD

**Issue by aviaoh** [kainosnoema/rack-lineprof#5]
hi @kainosnoema,
I recently saw your commits in my coveralls.io account:
![image](https://cloud.githubusercontent.com/assets/22256371/21893720/f4438d26-d8e4-11e6-965e-eb7b3630dd0f.png)

I also opened issue: https://github.com/lemurheavy/coveralls-public/issues/909
FYI.

**Comment by kainosnoema** [comment]
@aviaoh interesting. My commit there is actually on a public repo, over here: https://github.com/crepe/jsonite/commit/76a4d21d01f79fa51bd37ede00849460e356c485. Why it's showing up in coveralls.io on your account, I have no idea. But it's not leaking my private commits anyway.
